version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3307"

  app:
    build:
      context: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mysql
